#!/bin/bash

##############################################################
# lanceur de robygo
##############################################################

LOGGING="-Dlog4j.configuration=file:./config/logging.properties"
#JMX="-Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=1999 -Dcom.sun.management.jmxremote.authenticate=false "
JAR=`ls robygo*.jar`

java $VERBOSE $LOGGING -jar $JAR $*

